ProjectWebApp/urls.py
from django.urls import path
from ProjectWebApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name = "Home"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.blog, name = "Blog"),
    path('category/<int:category_id>/', views.category, name="category")
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add/<int:product_id>/", views.add_product, name="add"),
    path("delete/<int:product_id>/", views.delete_product, name="delete"),
    path("substract/<int:product_id>/", views.substract_product, name="substract"),
    path("empty/<int:product_id>/", views.empty_cart, name="empty"),

]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name = "Contact"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('', include('ProjectWebApp.urls')),

]

services/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.services, name = "Services"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name = "Shop"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length = 50)
    content = models.CharField(max_length = 50)
    image = models.ImageField(upload_to = 'blog', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
    
    def __str__(self):
        return self.title            

cart/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    title = models.CharField(max_length = 50)
    content = models.CharField(max_length = 50)
    image = models.ImageField(upload_to = 'services')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'service'
        verbose_name_plural = 'services'
    
    def __str__(self):
        return self.title
        

shop/models.py
from django.db import models

# Create your models here.

class CategoryProd(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name = "categoryProd"
        verbose_name_plural = "categoriesProd"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    categories = models.ForeignKey(CategoryProd, on_delete=models.CASCADE)
    img = models.ImageField(upload_to="shop", null=True, blank=True)
    price = models.FloatField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name = "product"
        verbose_name_plural = "products"

contact/forms.py
from django import forms

class FormContact(forms.Form):
    name = forms.CharField(label="Name", required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.CharField(label="Email", required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class':'form-control'}))

ProjectWebApp/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "ProjectWebApp/home.html")

blog/views.py
from django.shortcuts import render
from blog.models import Post, Category
# Create your views here.

def blog(request):
    posts = Post.objects.all()
    return render(request, "blog/blog.html", {"posts": posts})    

def category(request, category_id):
    category = Category.objects.get(id=category_id)
    posts = Post.objects.filter(categories = category)
    return render(request, "blog/categories.html", {'category': category, 'posts': posts})

cart/views.py
from django.shortcuts import render
from .cart import Cart
from shop.models import Product
from django.shortcuts import redirect

# Create your views here.

def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)

    return redirect("Shop")

def delete_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.delete(product=product)

    return redirect("Shop")

def substract_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.subtract(product=product)

    return redirect("Shop")

def empty_cart(request, product_id):
    cart = Cart(request)
    cart.emtpy_cart()

    return redirect("Shop")

contact/views.py
from django.shortcuts import render, redirect
from .forms import FormContact
from django.core.mail import EmailMessage

# Create your views here.
def contact(request):
    form_contact = FormContact()

    if request.method=='POST':
        form_contact = FormContact(data=request.POST)
        if form_contact.is_valid():
            name = request.POST.get("name")
            email = request.POST.get("email")
            content = request.POST.get("content")

            msg = EmailMessage(
                'Messaje from app',
                'The user {} with email {} write:\n\n {}'.format(name, email, content),
                '', 
                ['<put recipient email>'] # Change for the recipient email
            )

            try:
                msg.send()
                return redirect("/contact/?valid")          
            except:
                return redirect("/contact/?invalid")     

    return render(request, "contact/contact.html", {'form_contact': form_contact})  

services/views.py
from django.shortcuts import render
from services.models import Service

# Create your views here.
def services(request):
    services = Service.objects.all()
    return render(request, "services/services.html", {"services": services})

shop/views.py
from django.shortcuts import render
from .models import Product

# Create your views here.
def shop(request):

    products = Product.objects.all()
    return render(request, "shop/shop.html", {"products": products})

ProjectWebApp/templates/ProjectWebApp/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.0.2 -->
  <link rel="stylesheet" href="{% static 'ProjectWebApp/vendor/css/bootstrap.min.css' %}">

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lora&family=Raleway:wght@300&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lora&family=Raleway:wght@300&display=swap" rel="stylesheet">

  <!-- Styles -->
  <link rel="stylesheet" href="{% static 'ProjectWebApp/css/main.css' %}">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav me-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'Home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/services/' %}active{% endif %}" href="{% url 'Services' %}">Services <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/shop/' %}active{% endif %}" href="{% url 'Shop' %}">Shop <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:':6' == '/blog/' %}active{% endif %}" href="{% url 'Blog' %}">Blog <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/contact/' %}active{% endif %}" href="{% url 'Contact' %}">Contact <span class="visually-hidden">(current)</span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  </header>

  <main>
    <!-- Variable content -->
    {% block content %}

    {% endblock %}
  </main>

  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">test
        <a href="#" class="link">
          <span>
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-facebook fa-stack-1x"></i>
          </span>
        </a>
      </p>
    </div>
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="{% static 'ProjectWebApp/vendor/js/bootstrap.min.js' %}"></script>
</body>

</html>

ProjectWebApp/templates/ProjectWebApp/home.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

Home

{% endblock %}

blog/templates/blog/blog.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container padding-20">
    <div class="row">

        {% for post in posts %}

        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{% if post.image.url != null%}  {{post.image.url}} {% endif %}" class="card-img-top service-img" alt="">
                <div class="card-body">
                    <h5 class="card-title service-title">{{post.title}}</h5>
                    <p class="card-text">{{post.content}}</p>
                    <blockquote class="blockquote">
                        <p></p>
                        <footer class="blockquote-footer"> <cite title="Source Title">{{post.author}}</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>

    <section>
        <div style="width: 75%; margin: auto; text-align: center;">
            Categories: 

            {% for post in posts %}
                {% for category in post.categories.all %}
                   <a href="{% url 'category' category.id %}">{{category.name}}</a>  &nbsp;&nbsp;&nbsp;&nbsp;
                {% endfor %}    
            {% endfor %}
        </div>
    </section>

</div>

{% endblock %}

blog/templates/blog/categories.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container padding-20">
    <div class="row">

        {% for post in posts %}

        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{% if post.image.url != null%}  {{post.image.url}} {% endif %}" class="card-img-top service-img" alt="">
                <div class="card-body">
                    <h5 class="card-title service-title">{{post.title}}</h5>
                    <p class="card-text">{{post.content}}</p>
                    <blockquote class="blockquote">
                        <p></p>
                        <footer class="blockquote-footer"> <cite title="Source Title">{{post.author}}</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>

    <section>
        <div style="width: 75%; margin: auto; text-align: center;">
            Categories: 

            {% for post in posts %}
                {% for category in post.categories.all %}
                    {{category.name}} &nbsp;&nbsp;&nbsp;&nbsp;
                {% endfor %}    
            {% endfor %}
        </div>
    </section>

</div>

{% endblock %}

contact/templates/contact/contact.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

{% if "valid" in request.GET %}
<div class="alert alert-success" role="alert">
    The message has been sent successfully!
</div>
{% endif %}

<div class="container formContainer">
    <h1>Contact Form</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            {{form_contact.as_p}}
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

services/templates/services/services.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container padding-20">
    <div class="row">

        {% for service in services %}

        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{{service.image.url}}" class="card-img-top service-img" alt="">
                <div class="card-body">
                    <h5 class="card-title service-title">{{service.title}}</h5>
                    <p class="card-text">{{service.content}}</p>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>
{% endblock %}

shop/templates/cart/widget.html
<table style="margin: 5px 5px;" class="table table-bordered">
    <thead>
        <tr>
            <th colspan="3">Cart</th>
        </tr>
        <tr>
            <th>Product</th>
            <th>Amount</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{value.name}}</td>
                    <td>{{value.amount}}</td>
                    <td>
                        <a href="{% url 'cart:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'cart:substract' value.product_id %}" class="btn btn-sm btn-success">-</a><br>
                        {{value.price}}
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No products
                    </div>
                </td>
            </tr>
        {% endif %}

    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <p>Total: {{total_cart}} $</p>
            </td>
        </tr>
    </tfoot>
</table>

shop/templates/shop/shop.html
{% extends "ProjectWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <!-- 2 columns -->
    <div class="row row-cols-2">

        <!-- left side contain products list -->
        <div class="col-md-9"> 
            <div class="row row-cols-1 row-cols-md-3 g-4">

                {% for product in products %}
                    <div class="col">
                        <div class="card text-center" style="margin: 5px 5px;" >
                            <img class="card-img-top" src="{{product.img.url}}" alt="">
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <p class="card-text">{{product.price}}&nbsp;$</p>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'cart:add' product.id %}" class="btn btn-success">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>

        <!-- right side contain cart -->
        <div class="col-md-3" style="float: right;">
            
            {% include "cart/widget.html" %}
        </div>

    </div>
</div>

{% endblock %}